name: tobe_cv_flutter
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  cupertino_icons: ^1.0.6
  dart_code_metrics: ^5.7.6
  injectable_generator: ^2.4.1
  l: ^4.0.2
  injectable: ^2.3.2
  dio: ^5.4.0
  dio_intercept_to_curl: ^0.2.0
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  auto_route: ^7.8.4
  gap: ^3.0.1
  get_it: ^7.6.6
  reactive_forms: ^16.1.1

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.7
  flutter_gen_runner:
  flutter_test:
    sdk: flutter


  lint: ^2.3.0

flutter_gen:
  output: lib/presentation/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/